name: Compilar Sketches Arduino

on:
  push:
    paths:
      - '**.ino'

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false          # ← que compile todos aunque uno falle
      matrix:
        sketch:
          - Sketch_Parte1_LabMicro/Sketch_Parte1_LabMicro.ino
          - Sketch_Arduino1_Parte2/Sketch_Arduino1_Parte2.ino
          - Sketch_Arduino2_Parte2/Sketch_Arduino2_Parte2.ino

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Compilar ${{ matrix.sketch }}
        uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:uno'
          sketch-paths: ${{ matrix.sketch }}
          libraries: |
            - name: Keypad
            - name: LiquidCrystal I2C
              version: 1.1.4
            - name: Adafruit LiquidCrystal
